name: Build and Upload Unity Package
on:
  release:
    types: [published]
jobs:
  build-package:
    name: Build and Upload UnityPackage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      
      - name: Generate filtered file list
        uses: actions/github-script@v6
        id: filelist
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const path = require('path');
      
            const ignorePatterns = fs.readFileSync('.unitypackage-ignore', 'utf8')
              .split('\n')
              .map(line => line.trim())
              .filter(line => line && !line.startsWith('#'));
      
            const walk = (dir) => {
              let results = [];
              for (const file of fs.readdirSync(dir)) {
                const fullPath = path.join(dir, file);
                const relPath = path.relative('.', fullPath);
                if (ignorePatterns.some(p => relPath.startsWith(p) || new RegExp(p).test(relPath))) continue;
                const stat = fs.statSync(fullPath);
                if (stat.isDirectory()) {
                  results = results.concat(walk(fullPath));
                } else {
                  results.push(relPath);
                  if (fs.existsSync(`${fullPath}.meta`)) {
                    results.push(`${relPath}.meta`);
                  }
                }
              }
              return results;
            };
      
            let files;
            try {
              files = walk('.');
            } catch (err) {
              console.error('Error walking directory:', err);
              return '';
            }
      
            if (!Array.isArray(files)) {
              console.error('walk() did not return an array');
              return '';
            }
      
            // Write to file for the action to read
            fs.writeFileSync('fileList.txt', files.join('\n'));
            console.log(`Generated file list with ${files.length} files`);
            return files.join('\n');
      
      - name: Debug file list
        run: |
          echo "File count: $(wc -l < fileList.txt)"
          echo "First 10 files:"
          head -10 fileList.txt
      
      - name: Show filtered file list
        run: cat fileList.txt
      
      - name: Generate .unitypackage
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage"
          project-folder: "."
      
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: "Release ${{ github.event.release.tag_name }}"
          files: "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}