name: Build and Upload Unity Package
on:
  release:
    types: [published]
jobs:
  build-package:
    name: Build and Upload UnityPackage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      
      - name: Reorganize files with base PersistentId folder
        run: |
          echo "Creating PersistentId base folder structure..."
          
          # Create the base directory structure
          mkdir -p PersistentId
          
          # Function to check if a path should be ignored
          should_ignore() {
            local path="$1"
            if [ -f ".unitypackage-ignore" ]; then
              while IFS= read -r pattern; do
                # Skip empty lines and comments
                [[ -z "$pattern" || "$pattern" =~ ^#.*$ ]] && continue
                
                # Check if the path matches the pattern
                if [[ "$path" == $pattern* ]] || [[ "$path" =~ $pattern ]]; then
                  return 0  # Should ignore
                fi
              done < ".unitypackage-ignore"
            fi
            return 1  # Should not ignore
          }
          
          # Copy files and directories to PersistentId folder, excluding ignored items
          for item in *; do
            # Skip the PersistentId directory we just created and common Git/CI files
            [[ "$item" == "PersistentId" || "$item" == ".git" || "$item" == ".github" ]] && continue
            
            # Check if this item should be ignored
            if ! should_ignore "$item"; then
              echo "Copying $item to PersistentId/"
              cp -r "$item" "PersistentId/"
            else
              echo "Ignoring $item"
            fi
          done
          
          # Create .meta file for the PersistentId folder with a proper GUID
          # Try multiple methods to generate a GUID
          if command -v python3 &> /dev/null; then
            GUID=$(python3 -c "import uuid; print(uuid.uuid4().hex)")
          elif command -v uuidgen &> /dev/null; then
            GUID=$(uuidgen | tr -d '-' | tr '[:upper:]' '[:lower:]')
          else
            # Fallback: generate a pseudo-random 32-char hex string
            GUID=$(openssl rand -hex 16)
          fi
          
          cat > PersistentId.meta << EOF
          fileFormatVersion: 2
          guid: $GUID
          folderAsset: yes
          DefaultImporter:
            externalObjects: {}
            userData: 
            assetBundleName: 
            assetBundleVariant: 
          EOF
          
          echo "PersistentId folder structure created:"
          find PersistentId -type f | head -20
          
          echo "Verifying PersistentId.meta file:"
          if [ -f "PersistentId.meta" ]; then
            echo "PersistentId.meta created successfully"
            cat PersistentId.meta
          else
            echo "ERROR: PersistentId.meta not found!"
            exit 1
          fi
      
      - name: Generate filtered meta file list
        run: |
          echo "Starting file list generation from PersistentId folder..."
          
          # Initialize the meta list file
          > metaList
          
          # Function to check if a path should be ignored (keeping for consistency)
          should_ignore() {
            local path="$1"
            if [ -f ".unitypackage-ignore" ]; then
              while IFS= read -r pattern; do
                # Skip empty lines and comments
                [[ -z "$pattern" || "$pattern" =~ ^#.*$ ]] && continue
                
                # Check if the path matches the pattern
                if [[ "$path" == $pattern* ]] || [[ "$path" =~ $pattern ]]; then
                  return 0  # Should ignore
                fi
              done < ".unitypackage-ignore"
            fi
            return 1  # Should not ignore
          }
          
          # Add the PersistentId folder meta file first
          echo "PersistentId.meta" >> metaList
          echo "Including base folder: PersistentId.meta"
          
          echo "Finding all .meta files in PersistentId folder..."
          # Find all .meta files within the PersistentId folder
          while IFS= read -r -d '' metafile; do
            # Remove leading "./" 
            clean_path="${metafile#./}"
            
            echo "$clean_path" >> metaList
            echo "Including: $clean_path"
          done < <(find PersistentId -name "*.meta" -print0)
          
          echo "Finding directory .meta files in PersistentId..."
          # Find .meta files for directories within PersistentId
          while IFS= read -r -d '' dir; do
            # Skip the PersistentId root directory itself
            [[ "$dir" == "PersistentId" ]] && continue
            
            # Remove leading "./"
            clean_path="${dir#./}"
            
            # Check for corresponding .meta file for this directory
            if [ -f "${dir}.meta" ]; then
              meta_path="${clean_path}.meta"
              echo "$meta_path" >> metaList
              echo "Including directory meta: $meta_path"
            fi
          done < <(find PersistentId -type d -print0)
          
          # Remove any duplicate entries and sort
          sort metaList | uniq > metaList.tmp && mv metaList.tmp metaList
          
          echo ""
          echo "=== FINAL META LIST ==="
          cat metaList
          echo ""
          echo "Total entries: $(wc -l < metaList)"
          
          # Verify the file exists and has content
          if [ ! -s metaList ]; then
            echo "ERROR: metaList is empty!"
            exit 1
          fi
          
          echo "Final metaList size: $(wc -l < metaList) lines"
      
      - name: Debug ignore file content
        run: |
          if [ -f ".unitypackage-ignore" ]; then
            echo "=== UNITY PACKAGE IGNORE FILE CONTENT ==="
            cat .unitypackage-ignore
            echo "=== END IGNORE FILE ==="
          else
            echo "No .unitypackage-ignore file found"
          fi
      
      - name: Generate .unitypackage
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage"
          include-files: metaList
      
      - name: Verify package was created
        run: |
          if [ -f "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage" ]; then
            echo "Unity package created successfully!"
            ls -la "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage"
          else
            echo "ERROR: Unity package was not created!"
            exit 1
          fi
      
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: "Release ${{ github.event.release.tag_name }}"
          files: "com.proselyte.persistence-${{ github.event.release.tag_name }}.unitypackage"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}